// tools/neo4jTool.ts
import { createTool } from '@mastra/core/tools';
import { z } from 'zod';
import neo4j from 'neo4j-driver';

// 1. Initialize Driver
const driver = neo4j.driver(
    process.env.NEO4J_URI!,
    neo4j.auth.basic(process.env.NEO4J_USERNAME!, process.env.NEO4J_PASSWORD!)
);

export const executeNeo4jCypher = createTool({
    id: 'Execute Neo4j Cypher',
    description: 'Executes a read-only Cypher query against the knowledge graph to fetch data.',
    inputSchema: z.object({
        cypherQuery: z.string().describe('The read-only Cypher query to execute.'),
    }),
    execute: async ({ cypherQuery }) => {
        const session = driver.session();
        try {
            // Run the query generated by the LLM
            const result = await session.run(cypherQuery);

            // Clean up the Neo4j records into a standard JSON array for the LLM
            const data = result.records.map(record => {
                let row: any = {};
                record.keys.forEach(key => {
                    row[key] = record.get(key);
                });
                return row;
            });
            return data // This JSON goes back to the LLM
        } catch (error) {
            if (error instanceof Error) {
                return {
                    system_instruction: "The Cypher query failed. Read the error below, correct your Cypher syntax, and call this tool again.",
                    neo4j_error: error.message
                }
            } else {
                return { error: 'An unknown error occurred while executing the Cypher query.' }
            }
        } finally {
            await session.close();
        }
    },
});