export const DEFAULT_DUMMY_CHUNK_PATH = "src/docs/chunked/dummy.json"
export const ENTITY_EXTRACTION_CHUNK_PATH_ENV = "ENTITY_EXTRACTION_CHUNK_PATH"
export const ENTITY_EXTRACTION_DOC_PATH_ENV = "ENTITY_EXTRACTION_DOC_PATH"
